version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=97ba531fd2ebfa07436c93ce09244861
      - DB_NAME=db_desa_kauman
      - JWT_SECRET=${JWT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
    depends_on:
      - db
    volumes:
      - ./server/data:/usr/src/app/server/data
      - ./server/uploads:/usr/src/app/server/uploads
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=97ba531fd2ebfa07436c93ce09244861
      - MYSQL_DATABASE=db_desa_kauman
    volumes:
      - db_data:/var/lib/mysql
      # Map the SQL file to automatically import when container starts for the first time
      - ./maintenance/database/DataPenduduk2016.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  db_data:
